### ISSUE TITLE
Broadcast Punishment

### ISSUE THREAD

**Issue by luhandrew** [SilhouetteMC/Silhouette#2]
broadcastPunishment() broadcasts the player UUID, instead of the player name. It also shows that the player was punished by Console, even though it was punished by another player.

**Comment by UwUAroze** [comment]
Yeah we know, both of these issues are temporary. Silhouette isn't ready for public use yet!!

**Comment by luhandrew** [comment]
oh ok! i just came across this project, found it interesting and wanted to play around with it a little
